### PR TITLE
Milestone 3 Portfolio: Add a contact form 

### PR DESCRIPTION
**Pull request by michael-duke**
## Portfolio milestone 3: Add a contact form and finish the mobile version

 In this milestions I :
- Created forms with HTML5 validations.
- Understood the importance of UX.
- Understood how to parse a Figma design to create a UI.
- Learned how to collaborate.
- Lead the team in how to follow best collaboration practice according to Microverse.

### CODE REVIEW

**Comment by michael-duke** [comment]
**Dear, Reviewer**

Kindly give me some notes about using a little bit of JavaScript for the desktop version after this milestone. Is it allowed or forbidden. Thank you 😄

**Review by fobadara — APPROVED** [review]
# Approved
Hi @michael-duke, 

Good job so far!
There is nothing else to say other than merge it :shipit: 
## Highlights
✅ Linters are passing
✅ Good README
✅ Design matches template to a great extent
✅ Good pull request title and summary

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
[OPTIONAL] The background image for your site is not showing. Even though this is a requirement I have to approve your project since the reviewer for that section missed it when you submitted that section. I will suggest you still fix it to make your site more awesome.

[OPTIONAL] I think you should add images to your README because it is the first thing that anyone visiting your page will first see and it will definitely create a good impression if your designs are good

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by michael-duke** [comment]
> > **Dear, Reviewer**
> > Kindly give me some notes about using a little bit of JavaScript for the desktop version after this milestone. Is it allowed or forbidden. Thank you 😄
> 
> You have to be more explanatory. Using javascript in what sense? I will advise you to be more patient. You will get a lot of opportunities to use javaScript 👍🏽

>>Yes I mean for instance in template 1 the images, the titles and description in the work section for the desktop version are different from the mobile version. So I was thinking since we start from the latest milestone, you can use some JS to target the images titles and desctiption after a certain break point like 768px as it was mentioned.

**Comment by michael-duke** [comment]
@fobadara Thank you for the notes

I was using `background-image: url(/images/header-background.svg);` Although this runs well on live server so I changed it like so;
`background-image: url(../images/header-background.svg);` the `../` made a difference, do you approve

**Pull request merged**
